"""init app db

Revision ID: ca188da5bc25
Revises: 
Create Date: 2026-02-25 12:44:53.089024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca188da5bc25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_api_keys',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('service_name', sa.TEXT(), nullable=False),
    sa.Column('key_hash', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('service_api_keys_pkey')),
    sa.UniqueConstraint('service_name', name=op.f('service_api_keys_service_name_key')),
    schema='core'
    )
    with op.batch_alter_table('service_api_keys', schema='core') as batch_op:
        batch_op.create_index(batch_op.f('core_service_api_keys_id_idx'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('core_service_api_keys_key_hash_idx'), ['key_hash'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    schema='core'
    )
    with op.batch_alter_table('users', schema='core') as batch_op:
        batch_op.create_index(batch_op.f('core_users_email_idx'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('core_users_id_idx'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('core_users_username_idx'), ['username'], unique=True)

    op.create_table('user_profiles',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('user_id', sa.CHAR(length=26), nullable=False),
    sa.Column('first_name', sa.TEXT(), nullable=True),
    sa.Column('last_name', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('user_profiles_user_id_users_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_profiles_user_id_key')),
    schema='core'
    )
    with op.batch_alter_table('user_profiles', schema='core') as batch_op:
        batch_op.create_index(batch_op.f('core_user_profiles_id_idx'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema='core') as batch_op:
        batch_op.drop_index(batch_op.f('core_user_profiles_id_idx'))

    op.drop_table('user_profiles', schema='core')
    with op.batch_alter_table('users', schema='core') as batch_op:
        batch_op.drop_index(batch_op.f('core_users_username_idx'))
        batch_op.drop_index(batch_op.f('core_users_id_idx'))
        batch_op.drop_index(batch_op.f('core_users_email_idx'))

    op.drop_table('users', schema='core')
    with op.batch_alter_table('service_api_keys', schema='core') as batch_op:
        batch_op.drop_index(batch_op.f('core_service_api_keys_key_hash_idx'))
        batch_op.drop_index(batch_op.f('core_service_api_keys_id_idx'))

    op.drop_table('service_api_keys', schema='core')
    # ### end Alembic commands ###
