"""apikey model

Revision ID: e497b89cfc56
Revises: 
Create Date: 2026-02-05 23:31:52.648878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e497b89cfc56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_api_keys',
    sa.Column('id', sa.CHAR(length=26), nullable=False),
    sa.Column('service_name', sa.TEXT(), nullable=False),
    sa.Column('key_hash', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('service_api_keys_pkey')),
    sa.UniqueConstraint('service_name', name=op.f('service_api_keys_service_name_key'))
    )
    with op.batch_alter_table('service_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('service_api_keys_id_idx'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('service_api_keys_key_hash_idx'), ['key_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('service_api_keys_key_hash_idx'))
        batch_op.drop_index(batch_op.f('service_api_keys_id_idx'))

    op.drop_table('service_api_keys')
    # ### end Alembic commands ###
